name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run docker compose
      run: npm run docker:build
    - name: Install
      run: npm ci
    - name: Run tests
      run: npm run wdio:docker

    - name: Publishing Allure artifact to Github Actions
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: allure-report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}