name: Main
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16
        - name: Install
          run: npm install
        - name: Test
          run: npm run wdio
        - name: Publishing Allure artifact to Github Actions
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: allure-report
            path: allure-report
        - name: Deploy report
          uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
            branch: gh-pages
            folder: allure-report
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

